# Docker Compose override for .NET 8 + Node.js 10.13 projects
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dotnet.yml up

version: '3.8'

services:
  claude-bot:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dotnet
    container_name: claude-bot-dotnet
    
    environment:
      # .NET specific environment variables
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - NUGET_XMLDOC_MODE=skip
      
      # Node.js specific environment variables
      - NODE_ENV=development
      - NODE_VERSION=10.13
      
      # Claude Code environment (uses Node 18 internally)
      - CLAUDE_NODE_PATH=/usr/bin/node
    
    volumes:
      # Mount the target .NET project
      - ${PROJECT_PATH}:/workspace:cached
      
      # Mount bot configuration
      - ./config/project-config.dotnet.yml:/bot/config/project-config.yml:ro
      
      # Mount git configuration
      - ~/.gitconfig:/home/bot/.gitconfig:ro
      - ~/.ssh:/home/bot/.ssh:ro
      
      # Persistent data storage
      - bot-data-dotnet:/bot/data
      - bot-logs-dotnet:/bot/logs
      
      # .NET specific volumes
      - dotnet-nuget-cache:/home/bot/.nuget/packages
      - dotnet-tools-cache:/home/bot/.dotnet/tools
      
      # Node.js specific volumes
      - node-modules-cache:/workspace/node_modules
      - npm-cache:/home/bot/.npm
    
    working_dir: /workspace
    
    # Expose common ports for .NET development
    ports:
      - "5000:5000"    # Kestrel HTTP
      - "5001:5001"    # Kestrel HTTPS
      - "3000:3000"    # Node.js dev server
    
    # Health check for the bot service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  bot-data-dotnet:
    driver: local
  bot-logs-dotnet:
    driver: local
  dotnet-nuget-cache:
    driver: local
  dotnet-tools-cache:
    driver: local
  node-modules-cache:
    driver: local
  npm-cache:
    driver: local

networks:
  default:
    name: claude-bot-dotnet-network