# Docker Compose Override for Secrets Management
# Use with: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up -d

services:
  claude-bot-dynamic:
    secrets:
      - github_token
      - anthropic_api_key
    environment:
      # Override to read from secrets files
      - GITHUB_TOKEN_FILE=/run/secrets/github_token
      - ANTHROPIC_API_KEY_FILE=/run/secrets/anthropic_api_key

  claude-bot:
    secrets:
      - github_token
      - anthropic_api_key
    environment:
      - GITHUB_TOKEN_FILE=/run/secrets/github_token
      - ANTHROPIC_API_KEY_FILE=/run/secrets/anthropic_api_key

  claude-bot-dotnet:
    secrets:
      - github_token
      - anthropic_api_key
    environment:
      - GITHUB_TOKEN_FILE=/run/secrets/github_token
      - ANTHROPIC_API_KEY_FILE=/run/secrets/anthropic_api_key

secrets:
  github_token:
    external: true
  anthropic_api_key:
    external: true