# Platform Configuration for Claude Bot Infrastructure
# Defines supported platforms and their configurations

platforms:
  nodejs:
    name: "Node.js"
    version_command: "node --version"
    version_pattern: "v(\\d+\\.\\d+\\.\\d+)"
    default_version: "18.16.0"
    detect_files:
      - "package.json"
      - "package-lock.json"
      - "yarn.lock"
    build_commands:
      - "npm install"
      - "npm run build"
    test_commands:
      - "npm test"
    start_commands:
      - "npm start"
    dev_commands:
      - "npm run dev"

  python:
    name: "Python"
    version_command: "python3 --version"
    version_pattern: "Python (\\d+\\.\\d+\\.\\d+)"
    default_version: "3.8"
    detect_files:
      - "requirements.txt"
      - "pyproject.toml"
      - "setup.py"
      - "Pipfile"
    build_commands:
      - "pip install -r requirements.txt"
    test_commands:
      - "python -m pytest"
      - "python -m unittest"
    start_commands:
      - "python main.py"
      - "python app.py"

  dotnet:
    name: ".NET"
    version_command: "dotnet --version"
    version_pattern: "(\\d+\\.\\d+\\.\\d+)"
    default_version: "8.0"
    detect_files:
      - "*.csproj"
      - "*.fsproj"
      - "*.vbproj"
      - "*.sln"
    build_commands:
      - "dotnet restore"
      - "dotnet build"
    test_commands:
      - "dotnet test"
    start_commands:
      - "dotnet run"

# Default platform priorities (highest first)
priority:
  - nodejs
  - python
  - dotnet

# Platform-specific configuration
config:
  auto_detect: true
  parallel_builds: true
  max_build_time: 300  # seconds
  default_timeout: 120  # seconds