# Test Configuration for Node.js Test Project

project:
  name: "Node.js Test Project"
  repository: "yourusername/nodejs-test-repo"
  
  # Project-specific commands for testing
  build_command: "npm run build"
  test_command: "npm test"
  lint_command: "npm run lint"
  
  # Test project structure
  source_directories:
    - "."
    - "test/"
  
  exclude_patterns:
    - "node_modules/"
    - "*.log"

bot:
  labels:
    trigger: "claude-bot-test"
    priority_high: "priority:high"
    priority_low: "priority:low"
  
  # Relaxed settings for testing
  auto_merge: false
  require_tests: true
  run_build_before_pr: true
  
  # Test-specific Claude instructions
  context: |
    This is a simple Node.js test project for testing Claude Bot functionality.
    
    **Test Guidelines:**
    - Keep changes simple and focused
    - Always run tests after making changes
    - Use ES6+ features where appropriate
    - Add JSDoc comments for new functions
    - Follow existing code patterns

github:
  default_branch: "main"
  
  pr_template: |
    ## Automated Test Fix
    
    This PR was automatically generated by Claude Bot for testing purposes.
    
    ### Changes Made
    {changes_summary}
    
    ### Testing
    - [ ] Unit tests pass (`npm test`)
    - [ ] Linting passes (`npm run lint`)
    - [ ] Build succeeds (`npm run build`)
    
    **This is a test PR** - Please review and provide feedback to test the bot's response capabilities.
    
    Closes #{issue_number}