# Project-specific configuration for Claude Bot
# Copy this file to config/project-config.yml and customize

project:
  name: "My Project"
  repository: "owner/repo-name"
  
  # Project-specific paths and commands
  build_command: "npm run build"
  test_command: "npm test"
  lint_command: "npm run lint"
  
  # Directories to focus on for changes
  source_directories:
    - "src/"
    - "lib/"
    - "components/"
  
  # File patterns to exclude from bot changes
  exclude_patterns:
    - "*.lock"
    - "node_modules/"
    - "dist/"
    - "build/"

bot:
  # Custom labels for this project (inherits from .env if not set)
  labels:
    trigger: "claude-bot"
    priority_high: "priority:high"
    priority_low: "priority:low"
  
  # Project-specific bot behavior
  auto_merge: false
  require_tests: true
  run_build_before_pr: true
  
  # Custom Claude instructions for this project
  context: |
    This is a TypeScript/Angular project. Please:
    - Follow existing code patterns and conventions
    - Use camelCase for variables and functions
    - Add JSDoc comments for public methods
    - Ensure TypeScript types are properly defined
    - Run tests after making changes

github:
  # Default branch (usually main or master)
  default_branch: "main"
  
  # PR template customization
  pr_template: |
    ## Automated Fix
    
    This PR was automatically generated by Claude Bot to address issue #{issue_number}.
    
    ### Changes Made
    {changes_summary}
    
    ### Testing
    - [ ] Unit tests pass
    - [ ] Build succeeds
    - [ ] Manual testing completed
    
    ### Review Notes
    Please review the changes and provide feedback if adjustments are needed.
    The bot will automatically apply requested changes.
    
    Closes #{issue_number}